[package]
name = "coin-game"
version = "0.1.0"
edition = "2024"

[dependencies]
stunclient = "0.4.1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde_json = "1.0.143"
zod-rs = "0.1.0"
